version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: dev
      MONGODB_URL: mongodb://root:root@mongo:27017/app?authSource=admin
    command: >
      sh -lc "mkdir -p var/cache/dev/doctrine/odm/mongodb/Proxies var/log
      && chown -R 33:33 var
      && chmod -R u+rwX,go+rX var
      && exec php-fpm"
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mongo:
    image: mongo:7
    container_name: symfony-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost:27017", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  mongo-data:
