services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  php:
    build: ./docker/php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: howto

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongodata:
